### ISSUE TITLE
DevAPIKey

### ISSUE THREAD

**Issue by tungdt-90** [Quadra-Digital/silverstripe-mailchimp-module#4]
Can you explain why this module need to input another key in Dev mode? Because when i work on localhost, all my projects will always be in dev mode, and i can't see any benefit in this setting.

**Comment by HARVS1789UK** [comment]
Hi @tungdt-90, 

If we relied solely on the MailChimp API key stored in the database in both live and dev modes, then there is a very high chance of developers accidentally polluting/overwriting the live MailChimp accounts data.

I.E. you checkout your codebase locally, take a copy of your (or your clients) live database for local development, and start making changes to the Member or Subscriber records locally, you will be pushing this data to the live MC account.

This is easy to do by mistake in your own projects and even more likely to occur if you are taking on someone else project or vica versa.

We have therefore separated the API keys in to two sections 1) in the CMS the live MC accounts API Key can be entered. This can be done by the end user and no developer input is required. 2) The Dev API key in the config file, this can be inserted by a developer (or left as blank, the default, meaning no MC account is updated)

Personally we tend to use the same test/dev MC account for all our testing (we just reset the lists under that account each time we change site/client) so it made sense for us to set a default development MC account API Key in a config file. It also prevents any accidental pollution of the live MC account as mentioned above and means the developer is required to actually get involved in the module code and see how things are working.

**Comment by tungdt-90** [comment]
@HARVS1789UK 

I see !

I really never think about this before, but you just point out a nice thing for me here. But now i totally get it. 

Thank you for explaining this to me.

Have a nice working day !
